Update csn-project.yml

diff --git a/.github/workflows/csn-project.yml b/.github/workflows/csn-project.yml
--- a/.github/workflows/csn-project.yml
+++ b/.github/workflows/csn-project.yml
@@ -22,27 +22,27 @@ jobs:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
+    # - name: Set up Docker Buildx
+    #   uses: docker/setup-buildx-action@v2
 
-    - name: Install Docker Compose
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y docker-compose
+    # - name: Install Docker Compose
+    #   run: |
+    #     sudo apt-get update
+    #     sudo apt-get install -y docker-compose
 
-    - name: Build Docker image using docker-compose.local.yml
-      run: docker-compose -f docker-compose.local.yml build | tee docker-build-log.txt
+    # - name: Build Docker image using docker-compose.local.yml
+    #   run: docker-compose -f docker-compose.local.yml build | tee docker-build-log.txt
 
-    - name: Verify Docker image is built
-      run: |
-        docker images | grep brokencrystals_nodejs || { echo "Image brokencrystals_nodejs:latest not found."; exit 1; }
+    # - name: Verify Docker image is built
+    #   run: |
+    #     docker images | grep brokencrystals_nodejs || { echo "Image brokencrystals_nodejs:latest not found."; exit 1; }
 
-    - name: Tag Docker Image
-      run: |
-        docker tag brokencrystals_nodejs:latest docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/brokencrystals_nodejs:${{ github.sha }}
+    # - name: Tag Docker Image
+    #   run: |
+    #     docker tag brokencrystals_nodejs:latest docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/brokencrystals_nodejs:${{ github.sha }}
 
-    - name: Log in to Docker Hub
-      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
+    # - name: Log in to Docker Hub
+    #   run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
 
-    - name: Push Docker image to Docker Hub
-      run: docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/brokencrystals_nodejs:${{ github.sha }}
+    # - name: Push Docker image to Docker Hub
+    #   run: docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/brokencrystals_nodejs:${{ github.sha }}
