v3.1.1.1

diff --git a/.github/workflows/csn-project.yml b/.github/workflows/csn-project.yml
--- a/.github/workflows/csn-project.yml
+++ b/.github/workflows/csn-project.yml
@@ -27,28 +27,28 @@ jobs:
 
     - name: Verify Docker image is built
       run: |
-        docker images | grep brokencrystals || { echo "Image brokencrystals:latest not found."; exit 1; }
+        docker images | grepbrokencrystals_nodejs || { echo "Image brokencrystals_nodejs:latest not found."; exit 1; }
 
     - name: Tag Docker Image
       run: |
-        docker tag  brokencrystals:latest docker.io/ziemieu86/brokencrystals:${{ github.sha }}
+        docker tag  brokencrystals_nodejs:latest docker.io/ziemieu86/brokencrystals:${{ github.sha }}
 
     - name: Log in to Docker Hub
       run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
 
     - name: Push Docker image to Docker Hub
-      run: docker push docker.io/ziemieu86/brokencrystals:${{ github.sha }}
+      run: docker push docker.io/ziemieu86/brokencrystals_nodejs:${{ github.sha }}
 
     - name: Scan with Docker Scout
       run: |
         docker run --rm \
         -v /var/run/docker.sock:/var/run/docker.sock \
         docker/scout:latest \
-        scout docker.io/ziemieu86/brokencrystals:${{ github.sha }} --output scout-report.html
+        scout docker.io/ziemieu86/brokencrystals_nodejs:${{ github.sha }} --output scout-report.html
 
     - name: Scan Docker Image with Trivy
       run: |
-        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image docker.io/ziemieu86/brokencrystals:${{ github.sha }} \
+        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image docker.io/ziemieu86/brokencrystals_nodejs:${{ github.sha }} \
         --format template --template "@contrib/html.tpl" -o trivy-scan-report.html
 
     - name: Run OWASP ZAP DAST
