v1.1.5

diff --git a/.github/workflows/csn-project.yml b/.github/workflows/csn-project.yml
--- a/.github/workflows/csn-project.yml
+++ b/.github/workflows/csn-project.yml
@@ -36,11 +36,7 @@ jobs:
         sudo dpkg -i trivy.deb
         rm trivy.deb
 
-    #     echo 'export PATH="$HOME/.scout/bin:$PATH"' >> $GITHUB_ENV
-
     - name: Run Trivy
-      #   run: |
-      #     curl -sSL https://get.scoutapm.com/scout-install.sh | bash
       run: trivy fs . > trivyfs.txt
 
     - name: Commit Trivy Report
@@ -49,31 +45,30 @@ jobs:
         git config --local user.name "GitHub Action"
         git add trivyfs.txt
         git commit -m "Add Trivy scan report" --no-verify
-        git push origin HEAD:${{ github.ref }} # Push to the same branch
+        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
 
 
-# Optional Docker steps
-# - name: Set up Docker Buildx
-#   uses: docker/setup-buildx-action@v2
+    - name: Install Docker Compose
+      # Optional Docker steps
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v2
 
-# - name: Install Docker Compose
-#   run: |
-#     sudo apt-get update
-#     sudo apt-get install -y docker-compose
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y docker-compose
 
-# - name: Build Docker image using docker-compose.local.yml
-#   run: docker-compose -f docker-compose.local.yml build | tee docker-build-log.txt
+    - name: Build Docker image using docker-compose.local.yml
+      run: docker-compose -f docker-compose.local.yml --build
 
-# - name: Verify Docker image is built
-#   run: |
-#     docker images | grep brokencrystals_nodejs || { echo "Image brokencrystals_nodejs:latest not found."; exit 1; }
+    - name: Verify Docker image is built
+      run: |
+        docker images | grep brokencrystals_nodejs || { echo "Image brokencrystals_nodejs:latest not found."; exit 1; }
 
-# - name: Tag Docker Image
-#   run: |
-#     docker tag brokencrystals_nodejs:latest docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/brokencrystals_nodejs:${{ github.sha }}
+    - name: Tag Docker Image
+      run: |
+        docker tag brokencrystals_nodejs ziemieu86/brokencrystals_nodejs:latest
+        docker login -u ${{scrects.DOCKER_USERNAME}} -p ${{scrects.DOCKER_TOKEN}}
+        docker push  ziemieu86/brokencrystals_nodejs:latest
 
-# - name: Log in to Docker Hub
-#   run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
-
-# - name: Push Docker image to Docker Hub
-#   run: docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/brokencrystals_nodejs:${{ github.sha }}
+      # env:
+#   DOCKER_CLI_ACI: 1
